## M3C 2018 Lab 2 task 1

1) Use the *rand* function to generate a 3 x 3 matrix, N 

In [3]:
import numpy as np

N = np.random.rand(3,3)

2) Compute the eigenvalues and eigenvectors of N:

In [12]:
[e, x] = np.linalg.eig(N)
print(e)
print(x)

[ 1.64935018 -0.3133491   0.23392597]
[[-0.6900604  -0.60193217 -0.37577595]
 [-0.42306266  0.79767026 -0.5494277 ]
 [-0.58722621 -0.03741411  0.74627183]]


3) Verify that $\textrm{det}(N-\lambda_1 I)=0$ where $\lambda_1$ is the first eigenvalue of N:

In [24]:
print(np.linalg.det(N - np.linalg.multi_dot([e[0],np.eye(3,3)])))

5.92988697205e-16


4) Verify that $N v_1 = \lambda_1 v_1$ where $v_1$ is the first eigenvector of N:

In [25]:
print(np.linalg.norm(np.linalg.multi_dot([N,x[:,0]])-e[0]*x[:,0]))

2.48253415325e-16
